# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rostislav/Work/Github/SWallpaper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rostislav/Work/Github/SWallpaper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rostislav/Work/Github/SWallpaper/CMakeFiles /home/rostislav/Work/Github/SWallpaper/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rostislav/Work/Github/SWallpaper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SWallpaper

# Build rule for target.
SWallpaper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SWallpaper
.PHONY : SWallpaper

# fast build rule for target.
SWallpaper/fast:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/build
.PHONY : SWallpaper/fast

src/display/ImlibWallpaperDisplay.o: src/display/ImlibWallpaperDisplay.cpp.o

.PHONY : src/display/ImlibWallpaperDisplay.o

# target to build an object file
src/display/ImlibWallpaperDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/display/ImlibWallpaperDisplay.cpp.o
.PHONY : src/display/ImlibWallpaperDisplay.cpp.o

src/display/ImlibWallpaperDisplay.i: src/display/ImlibWallpaperDisplay.cpp.i

.PHONY : src/display/ImlibWallpaperDisplay.i

# target to preprocess a source file
src/display/ImlibWallpaperDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/display/ImlibWallpaperDisplay.cpp.i
.PHONY : src/display/ImlibWallpaperDisplay.cpp.i

src/display/ImlibWallpaperDisplay.s: src/display/ImlibWallpaperDisplay.cpp.s

.PHONY : src/display/ImlibWallpaperDisplay.s

# target to generate assembly for a file
src/display/ImlibWallpaperDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/display/ImlibWallpaperDisplay.cpp.s
.PHONY : src/display/ImlibWallpaperDisplay.cpp.s

src/display/XWallpaperDisplay.o: src/display/XWallpaperDisplay.cpp.o

.PHONY : src/display/XWallpaperDisplay.o

# target to build an object file
src/display/XWallpaperDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/display/XWallpaperDisplay.cpp.o
.PHONY : src/display/XWallpaperDisplay.cpp.o

src/display/XWallpaperDisplay.i: src/display/XWallpaperDisplay.cpp.i

.PHONY : src/display/XWallpaperDisplay.i

# target to preprocess a source file
src/display/XWallpaperDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/display/XWallpaperDisplay.cpp.i
.PHONY : src/display/XWallpaperDisplay.cpp.i

src/display/XWallpaperDisplay.s: src/display/XWallpaperDisplay.cpp.s

.PHONY : src/display/XWallpaperDisplay.s

# target to generate assembly for a file
src/display/XWallpaperDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/display/XWallpaperDisplay.cpp.s
.PHONY : src/display/XWallpaperDisplay.cpp.s

src/factory/ImlibFactory.o: src/factory/ImlibFactory.cpp.o

.PHONY : src/factory/ImlibFactory.o

# target to build an object file
src/factory/ImlibFactory.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/factory/ImlibFactory.cpp.o
.PHONY : src/factory/ImlibFactory.cpp.o

src/factory/ImlibFactory.i: src/factory/ImlibFactory.cpp.i

.PHONY : src/factory/ImlibFactory.i

# target to preprocess a source file
src/factory/ImlibFactory.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/factory/ImlibFactory.cpp.i
.PHONY : src/factory/ImlibFactory.cpp.i

src/factory/ImlibFactory.s: src/factory/ImlibFactory.cpp.s

.PHONY : src/factory/ImlibFactory.s

# target to generate assembly for a file
src/factory/ImlibFactory.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/factory/ImlibFactory.cpp.s
.PHONY : src/factory/ImlibFactory.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager/FileManager.o: src/manager/FileManager.cpp.o

.PHONY : src/manager/FileManager.o

# target to build an object file
src/manager/FileManager.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/manager/FileManager.cpp.o
.PHONY : src/manager/FileManager.cpp.o

src/manager/FileManager.i: src/manager/FileManager.cpp.i

.PHONY : src/manager/FileManager.i

# target to preprocess a source file
src/manager/FileManager.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/manager/FileManager.cpp.i
.PHONY : src/manager/FileManager.cpp.i

src/manager/FileManager.s: src/manager/FileManager.cpp.s

.PHONY : src/manager/FileManager.s

# target to generate assembly for a file
src/manager/FileManager.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/manager/FileManager.cpp.s
.PHONY : src/manager/FileManager.cpp.s

src/manager/WallpaperManager.o: src/manager/WallpaperManager.cpp.o

.PHONY : src/manager/WallpaperManager.o

# target to build an object file
src/manager/WallpaperManager.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/manager/WallpaperManager.cpp.o
.PHONY : src/manager/WallpaperManager.cpp.o

src/manager/WallpaperManager.i: src/manager/WallpaperManager.cpp.i

.PHONY : src/manager/WallpaperManager.i

# target to preprocess a source file
src/manager/WallpaperManager.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/manager/WallpaperManager.cpp.i
.PHONY : src/manager/WallpaperManager.cpp.i

src/manager/WallpaperManager.s: src/manager/WallpaperManager.cpp.s

.PHONY : src/manager/WallpaperManager.s

# target to generate assembly for a file
src/manager/WallpaperManager.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/manager/WallpaperManager.cpp.s
.PHONY : src/manager/WallpaperManager.cpp.s

src/wallpaper/ImlibWallpaperImage.o: src/wallpaper/ImlibWallpaperImage.cpp.o

.PHONY : src/wallpaper/ImlibWallpaperImage.o

# target to build an object file
src/wallpaper/ImlibWallpaperImage.cpp.o:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/wallpaper/ImlibWallpaperImage.cpp.o
.PHONY : src/wallpaper/ImlibWallpaperImage.cpp.o

src/wallpaper/ImlibWallpaperImage.i: src/wallpaper/ImlibWallpaperImage.cpp.i

.PHONY : src/wallpaper/ImlibWallpaperImage.i

# target to preprocess a source file
src/wallpaper/ImlibWallpaperImage.cpp.i:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/wallpaper/ImlibWallpaperImage.cpp.i
.PHONY : src/wallpaper/ImlibWallpaperImage.cpp.i

src/wallpaper/ImlibWallpaperImage.s: src/wallpaper/ImlibWallpaperImage.cpp.s

.PHONY : src/wallpaper/ImlibWallpaperImage.s

# target to generate assembly for a file
src/wallpaper/ImlibWallpaperImage.cpp.s:
	$(MAKE) -f CMakeFiles/SWallpaper.dir/build.make CMakeFiles/SWallpaper.dir/src/wallpaper/ImlibWallpaperImage.cpp.s
.PHONY : src/wallpaper/ImlibWallpaperImage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SWallpaper"
	@echo "... edit_cache"
	@echo "... src/display/ImlibWallpaperDisplay.o"
	@echo "... src/display/ImlibWallpaperDisplay.i"
	@echo "... src/display/ImlibWallpaperDisplay.s"
	@echo "... src/display/XWallpaperDisplay.o"
	@echo "... src/display/XWallpaperDisplay.i"
	@echo "... src/display/XWallpaperDisplay.s"
	@echo "... src/factory/ImlibFactory.o"
	@echo "... src/factory/ImlibFactory.i"
	@echo "... src/factory/ImlibFactory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager/FileManager.o"
	@echo "... src/manager/FileManager.i"
	@echo "... src/manager/FileManager.s"
	@echo "... src/manager/WallpaperManager.o"
	@echo "... src/manager/WallpaperManager.i"
	@echo "... src/manager/WallpaperManager.s"
	@echo "... src/wallpaper/ImlibWallpaperImage.o"
	@echo "... src/wallpaper/ImlibWallpaperImage.i"
	@echo "... src/wallpaper/ImlibWallpaperImage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

